service: aws-indra-reto

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30
  stage: dev
  region: us-east-1
  profile: custom-profile

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /